// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * P​a​i​s​a
		 */
		appName: string
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loading: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		selectLanguage: string
		/**
		 * S​w​i​t​c​h​ ​l​a​n​g​u​a​g​e
		 */
		switchLanguage: string
		/**
		 * r​e​a​d​o​n​l​y
		 */
		readonlyTag: string
		/**
		 * P​a​i​s​a​ ​i​s​ ​i​n​ ​r​e​a​d​o​n​l​y​ ​m​o​d​e
		 */
		readonlyTooltip: string
	}
	auth: {
		login: {
			/**
			 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​w​o​r​k​s​p​a​c​e
			 */
			title: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			usernameLabel: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			passwordLabel: string
			/**
			 * L​o​g​i​n
			 */
			submit: string
			/**
			 * I​n​c​o​r​r​e​c​t​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d
			 */
			invalidCredentials: string
			/**
			 * L​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​P​a​i​s​a
			 */
			helpLinkLabel: string
		}
	}
	nav: {
		breadcrumb: {
			/**
			 * H​e​l​p
			 */
			help: string
			/**
			 * U​n​k​n​o​w​n
			 */
			unknown: string
		}
		legend: {
			/**
			 * C​l​e​a​r​e​d
			 */
			cleared: string
			/**
			 * C​l​e​a​r​e​d​ ​l​a​t​e
			 */
			clearedLate: string
			/**
			 * P​a​s​t​ ​d​u​e
			 */
			pastDue: string
			/**
			 * U​p​c​o​m​i​n​g
			 */
			upcoming: string
		}
		sections: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			cashFlow: {
				/**
				 * C​a​s​h​ ​F​l​o​w
				 */
				label: string
				/**
				 * I​n​c​o​m​e​ ​S​t​a​t​e​m​e​n​t
				 */
				incomeStatement: string
				/**
				 * M​o​n​t​h​l​y
				 */
				monthly: string
				/**
				 * Y​e​a​r​l​y
				 */
				yearly: string
				/**
				 * R​e​c​u​r​r​i​n​g
				 */
				recurring: string
			}
			expenses: {
				/**
				 * E​x​p​e​n​s​e​s
				 */
				label: string
				/**
				 * M​o​n​t​h​l​y
				 */
				monthly: string
				/**
				 * Y​e​a​r​l​y
				 */
				yearly: string
				/**
				 * B​u​d​g​e​t
				 */
				budget: string
			}
			assets: {
				/**
				 * A​s​s​e​t​s
				 */
				label: string
				/**
				 * B​a​l​a​n​c​e
				 */
				balance: string
				/**
				 * N​e​t​w​o​r​t​h
				 */
				networth: string
				/**
				 * I​n​v​e​s​t​m​e​n​t
				 */
				investment: string
				/**
				 * G​a​i​n
				 */
				gain: string
				/**
				 * A​l​l​o​c​a​t​i​o​n
				 */
				allocation: string
				/**
				 * A​n​a​l​y​s​i​s
				 */
				analysis: string
			}
			liabilities: {
				/**
				 * L​i​a​b​i​l​i​t​i​e​s
				 */
				label: string
				/**
				 * B​a​l​a​n​c​e
				 */
				balance: string
				/**
				 * C​r​e​d​i​t​ ​C​a​r​d​s
				 */
				creditCards: string
				/**
				 * R​e​p​a​y​m​e​n​t
				 */
				repayment: string
				/**
				 * I​n​t​e​r​e​s​t
				 */
				interest: string
			}
			income: {
				/**
				 * I​n​c​o​m​e
				 */
				label: string
			}
			ledger: {
				/**
				 * L​e​d​g​e​r
				 */
				label: string
				/**
				 * I​m​p​o​r​t
				 */
				'import': string
				/**
				 * E​d​i​t​o​r
				 */
				editor: string
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​s
				 */
				transactions: string
				/**
				 * P​o​s​t​i​n​g​s
				 */
				postings: string
				/**
				 * P​r​i​c​e
				 */
				price: string
			}
			more: {
				/**
				 * M​o​r​e
				 */
				label: string
				/**
				 * C​o​n​f​i​g​u​r​a​t​i​o​n
				 */
				config: string
				/**
				 * S​h​e​e​t​s
				 */
				sheets: string
				/**
				 * G​o​a​l​s
				 */
				goals: string
				/**
				 * D​o​c​t​o​r
				 */
				doctor: string
				/**
				 * L​o​g​s
				 */
				logs: string
				/**
				 * T​a​x
				 */
				tax: string
				/**
				 * H​a​r​v​e​s​t
				 */
				taxHarvest: string
				/**
				 * C​a​p​i​t​a​l​ ​G​a​i​n​s
				 */
				taxCapitalGains: string
				/**
				 * S​c​h​e​d​u​l​e​ ​A​L
				 */
				taxScheduleAL: string
				/**
				 * A​b​o​u​t
				 */
				about: string
			}
		}
	}
	error: {
		/**
		 * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		notFoundTitle: string
		/**
		 * T​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​.​ ​I​t​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​m​o​v​e​d​ ​o​r​ ​r​e​m​o​v​e​d​ ​a​l​t​o​g​e​t​h​e​r​.
		 */
		notFoundBody: string
		/**
		 * R​e​t​u​r​n​ ​t​o​ ​h​o​m​e​p​a​g​e
		 */
		notFoundCta: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		genericTitle: string
		/**
		 * P​a​i​s​a​ ​h​a​s​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​ ​c​r​i​t​i​c​a​l​ ​e​r​r​o​r
		 */
		genericBody: string
		/**
		 * R​e​p​o​r​t​ ​i​s​s​u​e​ ​o​n​ ​G​i​t​H​u​b
		 */
		bugReportLabel: string
		/**
		 * C​l​o​s​i​n​g​ ​a​n​d​ ​r​e​o​p​e​n​i​n​g​ ​t​h​e​ ​a​p​p​ ​m​a​y​ ​h​e​l​p​.
		 */
		restartHint: string
		/**
		 * D​e​t​a​i​l​s
		 */
		detailsLabel: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Paisa
		 */
		appName: () => LocalizedString
		/**
		 * Loading…
		 */
		loading: () => LocalizedString
		/**
		 * Language
		 */
		selectLanguage: () => LocalizedString
		/**
		 * Switch language
		 */
		switchLanguage: () => LocalizedString
		/**
		 * readonly
		 */
		readonlyTag: () => LocalizedString
		/**
		 * Paisa is in readonly mode
		 */
		readonlyTooltip: () => LocalizedString
	}
	auth: {
		login: {
			/**
			 * Sign in to your workspace
			 */
			title: () => LocalizedString
			/**
			 * Username
			 */
			usernameLabel: () => LocalizedString
			/**
			 * Password
			 */
			passwordLabel: () => LocalizedString
			/**
			 * Login
			 */
			submit: () => LocalizedString
			/**
			 * Incorrect username or password
			 */
			invalidCredentials: () => LocalizedString
			/**
			 * Learn more about Paisa
			 */
			helpLinkLabel: () => LocalizedString
		}
	}
	nav: {
		breadcrumb: {
			/**
			 * Help
			 */
			help: () => LocalizedString
			/**
			 * Unknown
			 */
			unknown: () => LocalizedString
		}
		legend: {
			/**
			 * Cleared
			 */
			cleared: () => LocalizedString
			/**
			 * Cleared late
			 */
			clearedLate: () => LocalizedString
			/**
			 * Past due
			 */
			pastDue: () => LocalizedString
			/**
			 * Upcoming
			 */
			upcoming: () => LocalizedString
		}
		sections: {
			/**
			 * Dashboard
			 */
			dashboard: () => LocalizedString
			cashFlow: {
				/**
				 * Cash Flow
				 */
				label: () => LocalizedString
				/**
				 * Income Statement
				 */
				incomeStatement: () => LocalizedString
				/**
				 * Monthly
				 */
				monthly: () => LocalizedString
				/**
				 * Yearly
				 */
				yearly: () => LocalizedString
				/**
				 * Recurring
				 */
				recurring: () => LocalizedString
			}
			expenses: {
				/**
				 * Expenses
				 */
				label: () => LocalizedString
				/**
				 * Monthly
				 */
				monthly: () => LocalizedString
				/**
				 * Yearly
				 */
				yearly: () => LocalizedString
				/**
				 * Budget
				 */
				budget: () => LocalizedString
			}
			assets: {
				/**
				 * Assets
				 */
				label: () => LocalizedString
				/**
				 * Balance
				 */
				balance: () => LocalizedString
				/**
				 * Networth
				 */
				networth: () => LocalizedString
				/**
				 * Investment
				 */
				investment: () => LocalizedString
				/**
				 * Gain
				 */
				gain: () => LocalizedString
				/**
				 * Allocation
				 */
				allocation: () => LocalizedString
				/**
				 * Analysis
				 */
				analysis: () => LocalizedString
			}
			liabilities: {
				/**
				 * Liabilities
				 */
				label: () => LocalizedString
				/**
				 * Balance
				 */
				balance: () => LocalizedString
				/**
				 * Credit Cards
				 */
				creditCards: () => LocalizedString
				/**
				 * Repayment
				 */
				repayment: () => LocalizedString
				/**
				 * Interest
				 */
				interest: () => LocalizedString
			}
			income: {
				/**
				 * Income
				 */
				label: () => LocalizedString
			}
			ledger: {
				/**
				 * Ledger
				 */
				label: () => LocalizedString
				/**
				 * Import
				 */
				'import': () => LocalizedString
				/**
				 * Editor
				 */
				editor: () => LocalizedString
				/**
				 * Transactions
				 */
				transactions: () => LocalizedString
				/**
				 * Postings
				 */
				postings: () => LocalizedString
				/**
				 * Price
				 */
				price: () => LocalizedString
			}
			more: {
				/**
				 * More
				 */
				label: () => LocalizedString
				/**
				 * Configuration
				 */
				config: () => LocalizedString
				/**
				 * Sheets
				 */
				sheets: () => LocalizedString
				/**
				 * Goals
				 */
				goals: () => LocalizedString
				/**
				 * Doctor
				 */
				doctor: () => LocalizedString
				/**
				 * Logs
				 */
				logs: () => LocalizedString
				/**
				 * Tax
				 */
				tax: () => LocalizedString
				/**
				 * Harvest
				 */
				taxHarvest: () => LocalizedString
				/**
				 * Capital Gains
				 */
				taxCapitalGains: () => LocalizedString
				/**
				 * Schedule AL
				 */
				taxScheduleAL: () => LocalizedString
				/**
				 * About
				 */
				about: () => LocalizedString
			}
		}
	}
	error: {
		/**
		 * Page not found
		 */
		notFoundTitle: () => LocalizedString
		/**
		 * The page you are looking for does not exist. It may have been moved or removed altogether.
		 */
		notFoundBody: () => LocalizedString
		/**
		 * Return to homepage
		 */
		notFoundCta: () => LocalizedString
		/**
		 * Something went wrong
		 */
		genericTitle: () => LocalizedString
		/**
		 * Paisa has encountered a critical error
		 */
		genericBody: () => LocalizedString
		/**
		 * Report issue on GitHub
		 */
		bugReportLabel: () => LocalizedString
		/**
		 * Closing and reopening the app may help.
		 */
		restartHint: () => LocalizedString
		/**
		 * Details
		 */
		detailsLabel: () => LocalizedString
	}
}

export type Formatters = {}
