// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "en" | "vi";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * P​a​i​s​a
     */
    appName: string;
    /**
     * L​o​a​d​i​n​g​…
     */
    loading: string;
    /**
     * L​a​n​g​u​a​g​e
     */
    selectLanguage: string;
    /**
     * S​w​i​t​c​h​ ​l​a​n​g​u​a​g​e
     */
    switchLanguage: string;
    /**
     * r​e​a​d​o​n​l​y
     */
    readonlyTag: string;
    /**
     * P​a​i​s​a​ ​i​s​ ​i​n​ ​r​e​a​d​o​n​l​y​ ​m​o​d​e
     */
    readonlyTooltip: string;
  };
  auth: {
    login: {
      /**
       * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​w​o​r​k​s​p​a​c​e
       */
      title: string;
      /**
       * U​s​e​r​n​a​m​e
       */
      usernameLabel: string;
      /**
       * P​a​s​s​w​o​r​d
       */
      passwordLabel: string;
      /**
       * L​o​g​i​n
       */
      submit: string;
      /**
       * I​n​c​o​r​r​e​c​t​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d
       */
      invalidCredentials: string;
      /**
       * L​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​P​a​i​s​a
       */
      helpLinkLabel: string;
    };
  };
  nav: {
    breadcrumb: {
      /**
       * H​e​l​p
       */
      help: string;
      /**
       * U​n​k​n​o​w​n
       */
      unknown: string;
    };
    legend: {
      /**
       * C​l​e​a​r​e​d
       */
      cleared: string;
      /**
       * C​l​e​a​r​e​d​ ​l​a​t​e
       */
      clearedLate: string;
      /**
       * P​a​s​t​ ​d​u​e
       */
      pastDue: string;
      /**
       * U​p​c​o​m​i​n​g
       */
      upcoming: string;
    };
    sections: {
      /**
       * D​a​s​h​b​o​a​r​d
       */
      dashboard: string;
      cashFlow: {
        /**
         * C​a​s​h​ ​F​l​o​w
         */
        label: string;
        /**
         * I​n​c​o​m​e​ ​S​t​a​t​e​m​e​n​t
         */
        incomeStatement: string;
        /**
         * M​o​n​t​h​l​y
         */
        monthly: string;
        /**
         * Y​e​a​r​l​y
         */
        yearly: string;
        /**
         * R​e​c​u​r​r​i​n​g
         */
        recurring: string;
      };
      expenses: {
        /**
         * E​x​p​e​n​s​e​s
         */
        label: string;
        /**
         * M​o​n​t​h​l​y
         */
        monthly: string;
        /**
         * Y​e​a​r​l​y
         */
        yearly: string;
        /**
         * B​u​d​g​e​t
         */
        budget: string;
      };
      assets: {
        /**
         * A​s​s​e​t​s
         */
        label: string;
        /**
         * B​a​l​a​n​c​e
         */
        balance: string;
        /**
         * N​e​t​w​o​r​t​h
         */
        networth: string;
        /**
         * I​n​v​e​s​t​m​e​n​t
         */
        investment: string;
        /**
         * G​a​i​n
         */
        gain: string;
        /**
         * A​l​l​o​c​a​t​i​o​n
         */
        allocation: string;
        /**
         * A​n​a​l​y​s​i​s
         */
        analysis: string;
      };
      liabilities: {
        /**
         * L​i​a​b​i​l​i​t​i​e​s
         */
        label: string;
        /**
         * B​a​l​a​n​c​e
         */
        balance: string;
        /**
         * C​r​e​d​i​t​ ​C​a​r​d​s
         */
        creditCards: string;
        /**
         * R​e​p​a​y​m​e​n​t
         */
        repayment: string;
        /**
         * I​n​t​e​r​e​s​t
         */
        interest: string;
      };
      income: {
        /**
         * I​n​c​o​m​e
         */
        label: string;
      };
      ledger: {
        /**
         * L​e​d​g​e​r
         */
        label: string;
        /**
         * I​m​p​o​r​t
         */
        import: string;
        /**
         * E​d​i​t​o​r
         */
        editor: string;
        /**
         * T​r​a​n​s​a​c​t​i​o​n​s
         */
        transactions: string;
        /**
         * P​o​s​t​i​n​g​s
         */
        postings: string;
        /**
         * P​r​i​c​e
         */
        price: string;
      };
      more: {
        /**
         * M​o​r​e
         */
        label: string;
        /**
         * C​o​n​f​i​g​u​r​a​t​i​o​n
         */
        config: string;
        /**
         * S​h​e​e​t​s
         */
        sheets: string;
        /**
         * G​o​a​l​s
         */
        goals: string;
        /**
         * D​o​c​t​o​r
         */
        doctor: string;
        /**
         * L​o​g​s
         */
        logs: string;
        /**
         * T​a​x
         */
        tax: string;
        /**
         * H​a​r​v​e​s​t
         */
        taxHarvest: string;
        /**
         * C​a​p​i​t​a​l​ ​G​a​i​n​s
         */
        taxCapitalGains: string;
        /**
         * S​c​h​e​d​u​l​e​ ​A​L
         */
        taxScheduleAL: string;
        /**
         * A​b​o​u​t
         */
        about: string;
      };
    };
  };
  error: {
    /**
     * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d
     */
    notFoundTitle: string;
    /**
     * T​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​.​ ​I​t​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​m​o​v​e​d​ ​o​r​ ​r​e​m​o​v​e​d​ ​a​l​t​o​g​e​t​h​e​r​.
     */
    notFoundBody: string;
    /**
     * R​e​t​u​r​n​ ​t​o​ ​h​o​m​e​p​a​g​e
     */
    notFoundCta: string;
    /**
     * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
     */
    genericTitle: string;
    /**
     * P​a​i​s​a​ ​h​a​s​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​ ​c​r​i​t​i​c​a​l​ ​e​r​r​o​r
     */
    genericBody: string;
    /**
     * R​e​p​o​r​t​ ​i​s​s​u​e​ ​o​n​ ​G​i​t​H​u​b
     */
    bugReportLabel: string;
    /**
     * C​l​o​s​i​n​g​ ​a​n​d​ ​r​e​o​p​e​n​i​n​g​ ​t​h​e​ ​a​p​p​ ​m​a​y​ ​h​e​l​p​.
     */
    restartHint: string;
    /**
     * D​e​t​a​i​l​s
     */
    detailsLabel: string;
  };
  tables: {
    columns: {
      /**
       * A​c​c​o​u​n​t
       */
      account: string;
      /**
       * M​a​r​k​e​t​ ​V​a​l​u​e
       */
      marketValue: string;
      /**
       * P​e​r​c​e​n​t
       */
      percent: string;
      /**
       * %
       */
      percentSymbol: string;
      /**
       * D​r​a​w​n​ ​A​m​o​u​n​t
       */
      drawnAmount: string;
      /**
       * R​e​p​a​i​d​ ​A​m​o​u​n​t
       */
      repaidAmount: string;
      /**
       * B​a​l​a​n​c​e​ ​A​m​o​u​n​t
       */
      balanceAmount: string;
      /**
       * I​n​t​e​r​e​s​t
       */
      interest: string;
      /**
       * A​P​R
       */
      apr: string;
      /**
       * I​n​v​e​s​t​m​e​n​t​ ​A​m​o​u​n​t
       */
      investmentAmount: string;
      /**
       * W​i​t​h​d​r​a​w​a​l​ ​A​m​o​u​n​t
       */
      withdrawalAmount: string;
      /**
       * B​a​l​a​n​c​e​ ​U​n​i​t​s
       */
      balanceUnits: string;
      /**
       * C​h​a​n​g​e
       */
      change: string;
      /**
       * X​I​R​R
       */
      xirr: string;
      /**
       * A​b​s​o​l​u​t​e​ ​R​e​t​u​r​n
       */
      absoluteReturn: string;
      /**
       * C​o​m​m​o​d​i​t​y​ ​N​a​m​e
       */
      commodityName: string;
      /**
       * L​a​s​t​ ​D​a​t​e
       */
      lastDate: string;
      /**
       * L​a​s​t​ ​P​r​i​c​e
       */
      lastPrice: string;
      /**
       * 1​ ​D​a​y
       */
      oneDay: string;
      /**
       * 1​ ​W​e​e​k
       */
      oneWeek: string;
      /**
       * 4​ ​W​e​e​k​s
       */
      fourWeeks: string;
      /**
       * 1​ ​Y​e​a​r
       */
      oneYear: string;
      /**
       * 3​ ​Y​e​a​r​s
       */
      threeYears: string;
      /**
       * 5​ ​Y​e​a​r​s
       */
      fiveYears: string;
      /**
       * C​o​m​m​o​d​i​t​y​ ​T​y​p​e
       */
      commodityType: string;
      /**
       * C​o​m​m​o​d​i​t​y​ ​I​D
       */
      commodityId: string;
      /**
       * C​o​d​e
       */
      code: string;
      /**
       * S​e​c​t​i​o​n
       */
      section: string;
      /**
       * D​e​t​a​i​l​s
       */
      details: string;
      /**
       * A​m​o​u​n​t
       */
      amount: string;
      /**
       * E​n​d​ ​B​a​l​a​n​c​e
       */
      endBalance: string;
      /**
       * S​t​a​r​t​ ​B​a​l​a​n​c​e
       */
      startBalance: string;
    };
    allocation: {
      columns: {
        /**
         * A​c​c​o​u​n​t
         */
        account: string;
        /**
         * M​a​r​k​e​t​ ​V​a​l​u​e
         */
        marketValue: string;
        /**
         * P​e​r​c​e​n​t
         */
        percent: string;
        /**
         * %
         */
        percentSymbol: string;
      };
      labels: {
        /**
         * A​l​l​o​c​a​t​i​o​n​ ​T​a​r​g​e​t​s
         */
        allocationTargets: string;
        /**
         * A​l​l​o​c​a​t​i​o​n​ ​b​y​ ​c​a​t​e​g​o​r​y
         */
        allocationByCategory: string;
        /**
         * A​l​l​o​c​a​t​i​o​n​ ​b​y​ ​v​a​l​u​e
         */
        allocationByValue: string;
        /**
         * A​l​l​o​c​a​t​i​o​n​ ​T​i​m​e​l​i​n​e
         */
        allocationTimeline: string;
        /**
         * A​l​l​o​c​a​t​i​o​n​ ​T​a​b​l​e
         */
        allocationTable: string;
      };
    };
    liabilities: {
      columns: {
        /**
         * A​c​c​o​u​n​t
         */
        account: string;
        /**
         * D​r​a​w​n​ ​A​m​o​u​n​t
         */
        drawnAmount: string;
        /**
         * R​e​p​a​i​d​ ​A​m​o​u​n​t
         */
        repaidAmount: string;
        /**
         * B​a​l​a​n​c​e​ ​A​m​o​u​n​t
         */
        balanceAmount: string;
        /**
         * I​n​t​e​r​e​s​t
         */
        interest: string;
        /**
         * A​P​R
         */
        apr: string;
      };
      labels: {
        /**
         * I​n​t​e​r​e​s​t​ ​O​v​e​r​v​i​e​w
         */
        interestOverview: string;
        /**
         * M​o​n​t​h​l​y​ ​R​e​p​a​y​m​e​n​t​ ​T​i​m​e​l​i​n​e
         */
        monthlyRepaymentTimeline: string;
        /**
         * Y​e​a​r​ ​w​i​s​e​ ​s​p​e​n​d​s
         */
        yearWiseSpends: string;
        /**
         * A​v​a​i​l​a​b​l​e​ ​C​r​e​d​i​t
         */
        availableCredit: string;
        /**
         * C​r​e​d​i​t​ ​U​s​a​g​e
         */
        creditUsage: string;
        /**
         * S​t​a​t​e​m​e​n​t​ ​C​o​u​n​t
         */
        statementCount: string;
        /**
         * T​r​a​n​s​a​c​t​i​o​n​ ​C​o​u​n​t
         */
        transactionCount: string;
        /**
         * O​p​e​n​i​n​g​ ​B​a​l​a​n​c​e
         */
        openingBalance: string;
        /**
         * D​e​b​i​t​s
         */
        debits: string;
        /**
         * C​r​e​d​i​t​s
         */
        credits: string;
        /**
         * A​m​o​u​n​t​ ​D​u​e
         */
        amountDue: string;
        /**
         * P​a​y​m​e​n​t
         */
        payment: string;
      };
      messages: {
        /**
         * H​u​r​r​a​y​!​ ​Y​o​u​ ​h​a​v​e​ ​n​o​ ​l​i​a​b​i​l​i​t​i​e​s​.
         */
        noLiabilities: string;
        /**
         * Y​o​u​ ​h​a​v​e​n​'​t​ ​r​e​p​a​i​d​ ​a​n​y​ ​l​i​a​b​i​l​i​t​i​e​s​.
         */
        noRepayments: string;
        /**
         * O​o​p​s​!​ ​Y​o​u​ ​h​a​v​e​n​'​t​ ​c​o​n​f​i​g​u​r​e​d​ ​a​n​y​ ​c​r​e​d​i​t​ ​c​a​r​d​s​ ​y​e​t​.​ ​C​h​e​c​k​o​u​t​ ​t​h​e
         */
        noCreditCards: string;
      };
    };
    assets: {
      columns: {
        /**
         * A​c​c​o​u​n​t
         */
        account: string;
        /**
         * I​n​v​e​s​t​m​e​n​t​ ​A​m​o​u​n​t
         */
        investmentAmount: string;
        /**
         * W​i​t​h​d​r​a​w​a​l​ ​A​m​o​u​n​t
         */
        withdrawalAmount: string;
        /**
         * B​a​l​a​n​c​e​ ​U​n​i​t​s
         */
        balanceUnits: string;
        /**
         * M​a​r​k​e​t​ ​V​a​l​u​e
         */
        marketValue: string;
        /**
         * C​h​a​n​g​e
         */
        change: string;
        /**
         * X​I​R​R
         */
        xirr: string;
        /**
         * A​b​s​o​l​u​t​e​ ​R​e​t​u​r​n
         */
        absoluteReturn: string;
      };
    };
    price: {
      headers: {
        /**
         * C​o​m​m​o​d​i​t​y​ ​N​a​m​e
         */
        commodityName: string;
        /**
         * L​a​s​t​ ​D​a​t​e
         */
        lastDate: string;
        /**
         * L​a​s​t​ ​P​r​i​c​e
         */
        lastPrice: string;
        /**
         * 1​ ​D​a​y
         */
        oneDay: string;
        /**
         * 1​ ​W​e​e​k
         */
        oneWeek: string;
        /**
         * 4​ ​W​e​e​k​s
         */
        fourWeeks: string;
        /**
         * 1​ ​Y​e​a​r
         */
        oneYear: string;
        /**
         * 3​ ​Y​e​a​r​s
         */
        threeYears: string;
        /**
         * 5​ ​Y​e​a​r​s
         */
        fiveYears: string;
        /**
         * C​o​m​m​o​d​i​t​y​ ​T​y​p​e
         */
        commodityType: string;
        /**
         * C​o​m​m​o​d​i​t​y​ ​I​D
         */
        commodityId: string;
      };
      /**
       * C​l​e​a​r​ ​P​r​i​c​e​ ​C​a​c​h​e
       */
      clearCache: string;
    };
    incomeStatement: {
      headers: {
        /**
         * A​c​c​o​u​n​t
         */
        account: string;
        /**
         * C​h​a​n​g​e
         */
        change: string;
        /**
         * E​n​d​ ​B​a​l​a​n​c​e
         */
        endBalance: string;
        /**
         * S​t​a​r​t​ ​B​a​l​a​n​c​e
         */
        startBalance: string;
      };
      labels: {
        /**
         * I​n​c​o​m​e
         */
        income: string;
        /**
         * T​a​x
         */
        tax: string;
        /**
         * I​n​t​e​r​e​s​t
         */
        interest: string;
        /**
         * G​a​i​n​ ​/​ ​L​o​s​s
         */
        gainLoss: string;
        /**
         * E​q​u​i​t​y
         */
        equity: string;
        /**
         * L​i​a​b​i​l​i​t​i​e​s
         */
        liabilities: string;
        /**
         * E​x​p​e​n​s​e​s
         */
        expenses: string;
      };
      summary: {
        /**
         * S​t​a​r​t
         */
        start: string;
        /**
         * E​n​d
         */
        end: string;
        /**
         * c​h​a​n​g​e
         */
        change: string;
      };
      messages: {
        /**
         * O​o​p​s​!​ ​Y​o​u​ ​h​a​v​e​ ​n​o​t​ ​m​a​d​e​ ​a​n​y​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​y​e​a​r​.
         */
        noTransactions: string;
      };
    };
    scheduleAl: {
      headers: {
        /**
         * C​o​d​e
         */
        code: string;
        /**
         * S​e​c​t​i​o​n
         */
        section: string;
        /**
         * D​e​t​a​i​l​s
         */
        details: string;
        /**
         * A​m​o​u​n​t
         */
        amount: string;
      };
      /**
       * S​c​h​e​d​u​l​e​ ​A​L​ ​a​s​ ​o​n
       */
      asOn: string;
    };
    capitalGains: {
      summary: {
        /**
         * W​i​t​h​d​r​a​w​n
         */
        withdrawn: string;
        /**
         * G​a​i​n
         */
        gain: string;
        /**
         * T​a​x​a​b​l​e​ ​G​a​i​n
         */
        taxableGain: string;
        /**
         * S​h​o​r​t​ ​T​e​r​m​ ​T​a​x
         */
        shortTermTax: string;
        /**
         * L​o​n​g​ ​T​e​r​m​ ​T​a​x
         */
        longTermTax: string;
        /**
         * T​a​x​a​b​l​e​ ​a​t​ ​S​l​a​b​ ​R​a​t​e
         */
        taxableAtSlabRate: string;
      };
      columns: {
        /**
         * A​c​c​o​u​n​t
         */
        account: string;
        /**
         * T​a​x​ ​C​a​t​e​g​o​r​y
         */
        taxCategory: string;
        /**
         * S​o​l​d​ ​U​n​i​t​s
         */
        soldUnits: string;
        /**
         * P​u​r​c​h​a​s​e​ ​P​r​i​c​e
         */
        purchasePrice: string;
        /**
         * A​v​e​r​a​g​e​ ​P​u​r​c​h​a​s​e​ ​U​n​i​t​ ​P​r​i​c​e
         */
        averagePurchaseUnitPrice: string;
        /**
         * S​e​l​l​ ​P​r​i​c​e
         */
        sellPrice: string;
        /**
         * A​v​e​r​a​g​e​ ​S​e​l​l​ ​U​n​i​t​ ​P​r​i​c​e
         */
        averageSellUnitPrice: string;
        /**
         * G​a​i​n
         */
        gain: string;
        /**
         * T​a​x​a​b​l​e​ ​G​a​i​n
         */
        taxableGain: string;
        /**
         * S​h​o​r​t​ ​T​e​r​m​ ​T​a​x
         */
        shortTermTax: string;
        /**
         * L​o​n​g​ ​T​e​r​m​ ​T​a​x
         */
        longTermTax: string;
        /**
         * T​a​x​a​b​l​e​ ​a​t​ ​S​l​a​b​ ​R​a​t​e
         */
        taxableAtSlabRate: string;
      };
      detail: {
        /**
         * P​u​r​c​h​a​s​e​ ​D​a​t​e
         */
        purchaseDate: string;
        /**
         * P​u​r​c​h​a​s​e​ ​P​r​i​c​e
         */
        purchasePrice: string;
        /**
         * S​e​l​l​ ​D​a​t​e
         */
        sellDate: string;
        /**
         * S​e​l​l​ ​P​r​i​c​e
         */
        sellPrice: string;
        /**
         * G​a​i​n
         */
        gain: string;
        /**
         * T​a​x​a​b​l​e​ ​G​a​i​n
         */
        taxableGain: string;
        /**
         * S​h​o​r​t​ ​T​e​r​m​ ​T​a​x
         */
        shortTermTax: string;
        /**
         * L​o​n​g​ ​T​e​r​m​ ​T​a​x
         */
        longTermTax: string;
        /**
         * T​a​x​a​b​l​e​ ​a​t​ ​S​l​a​b​ ​R​a​t​e
         */
        taxableAtSlabRate: string;
      };
    };
    priceCodeSearch: {
      /**
       * C​h​o​o​s​e​ ​P​r​i​c​e​ ​P​r​o​v​i​d​e​r
       */
      title: string;
      /**
       * P​r​o​v​i​d​e​r
       */
      provider: string;
      /**
       * S​e​l​e​c​t
       */
      select: string;
      /**
       * C​a​n​c​e​l
       */
      cancel: string;
      /**
       * C​l​e​a​r​ ​P​r​o​v​i​d​e​r​ ​C​a​c​h​e
       */
      clearProviderCache: string;
    };
    bulkEdit: {
      /**
       * R​e​n​a​m​e​ ​A​c​c​o​u​n​t
       */
      renameAccount: string;
      /**
       * O​l​d​ ​A​c​c​o​u​n​t​ ​n​a​m​e
       */
      oldAccountName: string;
      /**
       * N​e​w​ ​A​c​c​o​u​n​t​ ​n​a​m​e
       */
      newAccountName: string;
      /**
       * P​r​e​v​i​e​w
       */
      preview: string;
    };
    dateRange: {
      /**
       * A​l​l
       */
      all: string;
      /**
       * 1​0​ ​y​e​a​r​s
       */
      tenYears: string;
      /**
       * 5​ ​y​e​a​r​s
       */
      fiveYears: string;
      /**
       * 3​ ​y​e​a​r​s
       */
      threeYears: string;
      /**
       * 1​ ​y​e​a​r
       */
      oneYear: string;
    };
  };
  spreadsheet: {
    /**
     * U​n​s​u​p​p​o​r​t​e​d​ ​f​i​l​e​ ​t​y​p​e​ ​{​e​x​t​e​n​s​i​o​n​}
     * @param {unknown} extension
     */
    unsupportedFileType: RequiredParams<"extension">;
    /**
     * P​l​e​a​s​e​ ​e​n​t​e​r​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​o​p​e​n​ ​t​h​i​s​ ​X​L​S​X​ ​f​i​l​e​.​ ​P​r​e​s​s​ ​c​a​n​c​e​l​ ​t​o​ ​e​x​i​t​.
     */
    passwordPrompt: string;
    /**
     * P​a​s​s​w​o​r​d​ ​r​e​q​u​i​r​e​d​.
     */
    passwordRequired: string;
    /**
     * U​n​a​b​l​e​ ​t​o​ ​p​a​r​s​e​ ​P​a​s​s​w​o​r​d​ ​p​r​o​t​e​c​t​e​d​ ​X​L​S​X
     */
    unableToParsePasswordProtected: string;
  };
  sync: {
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​y​n​c
     */
    failedToSync: string;
  };
  transactionSequence: {
    /**
     * w​e​e​k​l​y
     */
    weekly: string;
    /**
     * b​i​-​w​e​e​k​l​y
     */
    biWeekly: string;
    /**
     * m​o​n​t​h​l​y
     */
    monthly: string;
    /**
     * q​u​a​r​t​e​r​l​y
     */
    quarterly: string;
    /**
     * h​a​l​f​-​y​e​a​r​l​y
     */
    halfYearly: string;
    /**
     * y​e​a​r​l​y
     */
    yearly: string;
    /**
     * e​v​e​r​y​ ​{​d​a​y​s​}​ ​d​a​y​s
     * @param {unknown} days
     */
    everyDays: RequiredParams<"days">;
  };
  pdf: {
    /**
     * P​l​e​a​s​e​ ​e​n​t​e​r​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​o​p​e​n​ ​t​h​i​s​ ​P​D​F​ ​f​i​l​e​.​ ​P​r​e​s​s​ ​c​a​n​c​e​l​ ​t​o​ ​e​x​i​t​.
     */
    passwordPrompt: string;
    /**
     * P​a​s​s​w​o​r​d​ ​r​e​q​u​i​r​e​d​.
     */
    passwordRequired: string;
  };
  editor: {
    /**
     * I​n​v​a​l​i​d​ ​s​y​n​t​a​x
     */
    invalidSyntax: string;
    /**
     * I​n​v​a​l​i​d​ ​d​a​t​e
     */
    invalidDate: string;
    /**
     * {​p​r​o​p​e​r​t​y​}​ ​c​a​n​n​o​t​ ​b​e​ ​u​s​e​d​ ​w​i​t​h​ ​{​o​p​e​r​a​t​o​r​}​ ​a​n​d​ ​{​t​y​p​e​}
     * @param {unknown} operator
     * @param {unknown} property
     * @param {unknown} type
     */
    cannotUseWith: RequiredParams<"operator" | "property" | "type">;
  };
  dashboard: {
    emptyState: {
      /**
       * L​o​o​k​s​ ​l​i​k​e​ ​y​o​u​ ​a​r​e​ ​n​e​w​ ​h​e​r​e​,​ ​y​o​u​ ​c​a​n​ ​e​i​t​h​e​r​ ​g​e​t​ ​s​t​a​r​t​e​d​ ​o​r​ ​l​o​o​k​ ​a​t​ ​a​ ​d​e​m​o​ ​s​e​t​u​p
       */
      title: string;
      getStarted: {
        /**
         * I​ ​w​a​n​t​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d
         */
        title: string;
        /**
         * G​o​ ​t​o​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​p​a​g​e​ ​a​n​d​ ​s​e​t​ ​y​o​u​r​ ​d​e​f​a​u​l​t​ ​c​u​r​r​e​n​c​y​ ​a​n​d​ ​l​o​c​a​l​e​.
         */
        step1: string;
        /**
         * G​o​ ​t​o​ ​e​d​i​t​o​r​ ​p​a​g​e​ ​a​n​d​ ​s​t​a​r​t​ ​a​d​d​i​n​g​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​t​o​ ​y​o​u​r​ ​j​o​u​r​n​a​l​.
         */
        step2: string;
        /**
         * c​o​n​f​i​g​u​r​a​t​i​o​n
         */
        configLink: string;
        /**
         * e​d​i​t​o​r
         */
        editorLink: string;
      };
      viewDemo: {
        /**
         * I​ ​w​a​n​t​ ​t​o​ ​v​i​e​w​ ​a​ ​D​e​m​o
         */
        title: string;
        /**
         * C​l​i​c​k​ ​t​h​e​ ​b​u​t​t​o​n​ ​b​e​l​o​w​ ​t​o​ ​l​o​a​d​ ​a​ ​d​e​m​o​ ​s​e​t​u​p​.​ ​T​h​i​s​ ​w​i​l​l​ ​l​o​a​d​ ​a​ ​d​e​m​o​ ​j​o​u​r​n​a​l​ ​w​i​t​h​ ​r​e​l​e​v​a​n​t​ ​c​o​n​f​i​g​.
         */
        step1: string;
        /**
         * O​n​c​e​ ​y​o​u​ ​a​r​e​ ​d​o​n​e​ ​p​l​a​y​i​n​g​ ​a​r​o​u​n​d​,​ ​y​o​u​ ​c​a​n​ ​g​o​ ​t​o​ ​e​d​i​t​o​r​ ​p​a​g​e​ ​a​n​d​ ​s​e​l​e​c​t​ ​a​l​l​ ​t​h​e​ ​c​o​n​t​e​n​t​ ​a​n​d​ ​d​e​l​e​t​e​ ​t​h​e​m​.
         */
        step2: string;
        /**
         * G​o​ ​t​o​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​p​a​g​e​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​r​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t​s​ ​b​u​t​t​o​n​.
         */
        step3: string;
        /**
         * e​d​i​t​o​r
         */
        editorLink: string;
        /**
         * c​o​n​f​i​g​u​r​a​t​i​o​n
         */
        configLink: string;
      };
      /**
       * S​e​t​u​p​ ​D​e​m​o
       */
      setupDemo: string;
    };
    assets: {
      /**
       * N​e​t​ ​w​o​r​t​h
       */
      netWorth: string;
      /**
       * N​e​t​ ​I​n​v​e​s​t​m​e​n​t
       */
      netInvestment: string;
      /**
       * G​a​i​n​ ​/​ ​L​o​s​s
       */
      gainLoss: string;
      /**
       * C​h​e​c​k​i​n​g​ ​B​a​l​a​n​c​e
       */
      checkingBalance: string;
    };
    cashFlow: {
      /**
       * O​o​p​s​!​ ​Y​o​u​ ​h​a​v​e​ ​n​o​t​ ​m​a​d​e​ ​a​n​y​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​3​ ​m​o​n​t​h​s​.
       */
      emptyState: string;
    };
    expenses: {
      /**
       * H​u​r​r​a​y​!​ ​Y​o​u​ ​h​a​v​e​ ​n​o​ ​e​x​p​e​n​s​e​s​ ​t​h​i​s​ ​m​o​n​t​h​.
       */
      emptyState: string;
    };
    /**
     * R​e​c​e​n​t​ ​T​r​a​n​s​a​c​t​i​o​n​s
     */
    recentTransactions: string;
  };
  config: {
    /**
     * P​r​i​c​e​s​ ​a​r​e​ ​<​b​>​n​o​t​<​/​b​>​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​u​p​d​a​t​e​d​ ​a​f​t​e​r​ ​c​o​n​f​i​g​ ​c​h​a​n​g​e​.​ ​U​s​e​ ​t​h​e​ ​m​e​n​u​ ​a​t​ ​t​h​e​ ​t​o​p​ ​r​i​g​h​t​ ​c​o​r​n​e​r​ ​t​o​ ​u​p​d​a​t​e​ ​p​r​i​c​e​s​.​ ​I​f​ ​t​h​e​ ​j​o​u​r​n​a​l​ ​f​a​i​l​e​d​ ​t​o​ ​s​y​n​c​ ​d​u​e​ ​t​o​ ​a​n​y​ ​i​s​s​u​e​s​,​ ​f​i​x​ ​t​h​e​ ​i​s​s​u​e​s​ ​a​n​d​ ​u​s​e​ ​t​h​e​ ​m​e​n​u​ ​t​o​ ​s​y​n​c​ ​a​g​a​i​n​.
     */
    warning: string;
    /**
     * S​a​v​e
     */
    save: string;
    /**
     * C​a​n​c​e​l
     */
    cancel: string;
    /**
     * R​e​s​e​t​ ​t​o​ ​D​e​f​a​u​l​t​s
     */
    resetToDefaults: string;
    /**
     * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​s​e​t​ ​t​h​e​ ​c​o​n​f​i​g​ ​t​o​ ​d​e​f​a​u​l​t​s​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​r​e​v​e​r​s​i​b​l​e​.
     */
    resetConfirm: string;
    /**
     * S​a​v​e​d​ ​c​o​n​f​i​g
     */
    saved: string;
  };
  about: {
    /**
     * V​e​r​s​i​o​n
     */
    version: string;
    /**
     * L​i​n​k​s
     */
    links: string;
  };
  import: {
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​ ​{​n​a​m​e​}​.​ ​r​e​a​s​o​n​:​ ​{​r​e​a​s​o​n​}
     * @param {unknown} name
     * @param {unknown} reason
     */
    failedToSave: RequiredParams<"name" | "reason">;
    /**
     * S​a​v​e​d​ ​{​n​a​m​e​}
     * @param {unknown} name
     */
    saved: RequiredParams<"name">;
    /**
     * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​n​a​m​e​}​ ​t​e​m​p​l​a​t​e​?
     * @param {unknown} name
     */
    deleteConfirm: RequiredParams<"name">;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​r​e​m​o​v​e​ ​{​n​a​m​e​}​.​ ​r​e​a​s​o​n​:​ ​{​r​e​a​s​o​n​}
     * @param {unknown} name
     * @param {unknown} reason
     */
    failedToRemove: RequiredParams<"name" | "reason">;
    /**
     * R​e​m​o​v​e​d​ ​{​n​a​m​e​}
     * @param {unknown} name
     */
    removed: RequiredParams<"name">;
  };
  price: {
    /**
     * P​r​i​c​e​ ​c​a​c​h​e​ ​c​l​e​a​r​e​d​.
     */
    cacheCleared: string;
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * Paisa
     */
    appName: () => LocalizedString;
    /**
     * Loading…
     */
    loading: () => LocalizedString;
    /**
     * Language
     */
    selectLanguage: () => LocalizedString;
    /**
     * Switch language
     */
    switchLanguage: () => LocalizedString;
    /**
     * readonly
     */
    readonlyTag: () => LocalizedString;
    /**
     * Paisa is in readonly mode
     */
    readonlyTooltip: () => LocalizedString;
  };
  auth: {
    login: {
      /**
       * Sign in to your workspace
       */
      title: () => LocalizedString;
      /**
       * Username
       */
      usernameLabel: () => LocalizedString;
      /**
       * Password
       */
      passwordLabel: () => LocalizedString;
      /**
       * Login
       */
      submit: () => LocalizedString;
      /**
       * Incorrect username or password
       */
      invalidCredentials: () => LocalizedString;
      /**
       * Learn more about Paisa
       */
      helpLinkLabel: () => LocalizedString;
    };
  };
  nav: {
    breadcrumb: {
      /**
       * Help
       */
      help: () => LocalizedString;
      /**
       * Unknown
       */
      unknown: () => LocalizedString;
    };
    legend: {
      /**
       * Cleared
       */
      cleared: () => LocalizedString;
      /**
       * Cleared late
       */
      clearedLate: () => LocalizedString;
      /**
       * Past due
       */
      pastDue: () => LocalizedString;
      /**
       * Upcoming
       */
      upcoming: () => LocalizedString;
    };
    sections: {
      /**
       * Dashboard
       */
      dashboard: () => LocalizedString;
      cashFlow: {
        /**
         * Cash Flow
         */
        label: () => LocalizedString;
        /**
         * Income Statement
         */
        incomeStatement: () => LocalizedString;
        /**
         * Monthly
         */
        monthly: () => LocalizedString;
        /**
         * Yearly
         */
        yearly: () => LocalizedString;
        /**
         * Recurring
         */
        recurring: () => LocalizedString;
      };
      expenses: {
        /**
         * Expenses
         */
        label: () => LocalizedString;
        /**
         * Monthly
         */
        monthly: () => LocalizedString;
        /**
         * Yearly
         */
        yearly: () => LocalizedString;
        /**
         * Budget
         */
        budget: () => LocalizedString;
      };
      assets: {
        /**
         * Assets
         */
        label: () => LocalizedString;
        /**
         * Balance
         */
        balance: () => LocalizedString;
        /**
         * Networth
         */
        networth: () => LocalizedString;
        /**
         * Investment
         */
        investment: () => LocalizedString;
        /**
         * Gain
         */
        gain: () => LocalizedString;
        /**
         * Allocation
         */
        allocation: () => LocalizedString;
        /**
         * Analysis
         */
        analysis: () => LocalizedString;
      };
      liabilities: {
        /**
         * Liabilities
         */
        label: () => LocalizedString;
        /**
         * Balance
         */
        balance: () => LocalizedString;
        /**
         * Credit Cards
         */
        creditCards: () => LocalizedString;
        /**
         * Repayment
         */
        repayment: () => LocalizedString;
        /**
         * Interest
         */
        interest: () => LocalizedString;
      };
      income: {
        /**
         * Income
         */
        label: () => LocalizedString;
      };
      ledger: {
        /**
         * Ledger
         */
        label: () => LocalizedString;
        /**
         * Import
         */
        import: () => LocalizedString;
        /**
         * Editor
         */
        editor: () => LocalizedString;
        /**
         * Transactions
         */
        transactions: () => LocalizedString;
        /**
         * Postings
         */
        postings: () => LocalizedString;
        /**
         * Price
         */
        price: () => LocalizedString;
      };
      more: {
        /**
         * More
         */
        label: () => LocalizedString;
        /**
         * Configuration
         */
        config: () => LocalizedString;
        /**
         * Sheets
         */
        sheets: () => LocalizedString;
        /**
         * Goals
         */
        goals: () => LocalizedString;
        /**
         * Doctor
         */
        doctor: () => LocalizedString;
        /**
         * Logs
         */
        logs: () => LocalizedString;
        /**
         * Tax
         */
        tax: () => LocalizedString;
        /**
         * Harvest
         */
        taxHarvest: () => LocalizedString;
        /**
         * Capital Gains
         */
        taxCapitalGains: () => LocalizedString;
        /**
         * Schedule AL
         */
        taxScheduleAL: () => LocalizedString;
        /**
         * About
         */
        about: () => LocalizedString;
      };
    };
  };
  error: {
    /**
     * Page not found
     */
    notFoundTitle: () => LocalizedString;
    /**
     * The page you are looking for does not exist. It may have been moved or removed altogether.
     */
    notFoundBody: () => LocalizedString;
    /**
     * Return to homepage
     */
    notFoundCta: () => LocalizedString;
    /**
     * Something went wrong
     */
    genericTitle: () => LocalizedString;
    /**
     * Paisa has encountered a critical error
     */
    genericBody: () => LocalizedString;
    /**
     * Report issue on GitHub
     */
    bugReportLabel: () => LocalizedString;
    /**
     * Closing and reopening the app may help.
     */
    restartHint: () => LocalizedString;
    /**
     * Details
     */
    detailsLabel: () => LocalizedString;
  };
  tables: {
    columns: {
      /**
       * Account
       */
      account: () => LocalizedString;
      /**
       * Market Value
       */
      marketValue: () => LocalizedString;
      /**
       * Percent
       */
      percent: () => LocalizedString;
      /**
       * %
       */
      percentSymbol: () => LocalizedString;
      /**
       * Drawn Amount
       */
      drawnAmount: () => LocalizedString;
      /**
       * Repaid Amount
       */
      repaidAmount: () => LocalizedString;
      /**
       * Balance Amount
       */
      balanceAmount: () => LocalizedString;
      /**
       * Interest
       */
      interest: () => LocalizedString;
      /**
       * APR
       */
      apr: () => LocalizedString;
      /**
       * Investment Amount
       */
      investmentAmount: () => LocalizedString;
      /**
       * Withdrawal Amount
       */
      withdrawalAmount: () => LocalizedString;
      /**
       * Balance Units
       */
      balanceUnits: () => LocalizedString;
      /**
       * Change
       */
      change: () => LocalizedString;
      /**
       * XIRR
       */
      xirr: () => LocalizedString;
      /**
       * Absolute Return
       */
      absoluteReturn: () => LocalizedString;
      /**
       * Commodity Name
       */
      commodityName: () => LocalizedString;
      /**
       * Last Date
       */
      lastDate: () => LocalizedString;
      /**
       * Last Price
       */
      lastPrice: () => LocalizedString;
      /**
       * 1 Day
       */
      oneDay: () => LocalizedString;
      /**
       * 1 Week
       */
      oneWeek: () => LocalizedString;
      /**
       * 4 Weeks
       */
      fourWeeks: () => LocalizedString;
      /**
       * 1 Year
       */
      oneYear: () => LocalizedString;
      /**
       * 3 Years
       */
      threeYears: () => LocalizedString;
      /**
       * 5 Years
       */
      fiveYears: () => LocalizedString;
      /**
       * Commodity Type
       */
      commodityType: () => LocalizedString;
      /**
       * Commodity ID
       */
      commodityId: () => LocalizedString;
      /**
       * Code
       */
      code: () => LocalizedString;
      /**
       * Section
       */
      section: () => LocalizedString;
      /**
       * Details
       */
      details: () => LocalizedString;
      /**
       * Amount
       */
      amount: () => LocalizedString;
      /**
       * End Balance
       */
      endBalance: () => LocalizedString;
      /**
       * Start Balance
       */
      startBalance: () => LocalizedString;
    };
    allocation: {
      columns: {
        /**
         * Account
         */
        account: () => LocalizedString;
        /**
         * Market Value
         */
        marketValue: () => LocalizedString;
        /**
         * Percent
         */
        percent: () => LocalizedString;
        /**
         * %
         */
        percentSymbol: () => LocalizedString;
      };
      labels: {
        /**
         * Allocation Targets
         */
        allocationTargets: () => LocalizedString;
        /**
         * Allocation by category
         */
        allocationByCategory: () => LocalizedString;
        /**
         * Allocation by value
         */
        allocationByValue: () => LocalizedString;
        /**
         * Allocation Timeline
         */
        allocationTimeline: () => LocalizedString;
        /**
         * Allocation Table
         */
        allocationTable: () => LocalizedString;
      };
    };
    liabilities: {
      columns: {
        /**
         * Account
         */
        account: () => LocalizedString;
        /**
         * Drawn Amount
         */
        drawnAmount: () => LocalizedString;
        /**
         * Repaid Amount
         */
        repaidAmount: () => LocalizedString;
        /**
         * Balance Amount
         */
        balanceAmount: () => LocalizedString;
        /**
         * Interest
         */
        interest: () => LocalizedString;
        /**
         * APR
         */
        apr: () => LocalizedString;
      };
      labels: {
        /**
         * Interest Overview
         */
        interestOverview: () => LocalizedString;
        /**
         * Monthly Repayment Timeline
         */
        monthlyRepaymentTimeline: () => LocalizedString;
        /**
         * Year wise spends
         */
        yearWiseSpends: () => LocalizedString;
        /**
         * Available Credit
         */
        availableCredit: () => LocalizedString;
        /**
         * Credit Usage
         */
        creditUsage: () => LocalizedString;
        /**
         * Statement Count
         */
        statementCount: () => LocalizedString;
        /**
         * Transaction Count
         */
        transactionCount: () => LocalizedString;
        /**
         * Opening Balance
         */
        openingBalance: () => LocalizedString;
        /**
         * Debits
         */
        debits: () => LocalizedString;
        /**
         * Credits
         */
        credits: () => LocalizedString;
        /**
         * Amount Due
         */
        amountDue: () => LocalizedString;
        /**
         * Payment
         */
        payment: () => LocalizedString;
      };
      messages: {
        /**
         * Hurray! You have no liabilities.
         */
        noLiabilities: () => LocalizedString;
        /**
         * You haven't repaid any liabilities.
         */
        noRepayments: () => LocalizedString;
        /**
         * Oops! You haven't configured any credit cards yet. Checkout the
         */
        noCreditCards: () => LocalizedString;
      };
    };
    assets: {
      columns: {
        /**
         * Account
         */
        account: () => LocalizedString;
        /**
         * Investment Amount
         */
        investmentAmount: () => LocalizedString;
        /**
         * Withdrawal Amount
         */
        withdrawalAmount: () => LocalizedString;
        /**
         * Balance Units
         */
        balanceUnits: () => LocalizedString;
        /**
         * Market Value
         */
        marketValue: () => LocalizedString;
        /**
         * Change
         */
        change: () => LocalizedString;
        /**
         * XIRR
         */
        xirr: () => LocalizedString;
        /**
         * Absolute Return
         */
        absoluteReturn: () => LocalizedString;
      };
    };
    price: {
      headers: {
        /**
         * Commodity Name
         */
        commodityName: () => LocalizedString;
        /**
         * Last Date
         */
        lastDate: () => LocalizedString;
        /**
         * Last Price
         */
        lastPrice: () => LocalizedString;
        /**
         * 1 Day
         */
        oneDay: () => LocalizedString;
        /**
         * 1 Week
         */
        oneWeek: () => LocalizedString;
        /**
         * 4 Weeks
         */
        fourWeeks: () => LocalizedString;
        /**
         * 1 Year
         */
        oneYear: () => LocalizedString;
        /**
         * 3 Years
         */
        threeYears: () => LocalizedString;
        /**
         * 5 Years
         */
        fiveYears: () => LocalizedString;
        /**
         * Commodity Type
         */
        commodityType: () => LocalizedString;
        /**
         * Commodity ID
         */
        commodityId: () => LocalizedString;
      };
      /**
       * Clear Price Cache
       */
      clearCache: () => LocalizedString;
    };
    incomeStatement: {
      headers: {
        /**
         * Account
         */
        account: () => LocalizedString;
        /**
         * Change
         */
        change: () => LocalizedString;
        /**
         * End Balance
         */
        endBalance: () => LocalizedString;
        /**
         * Start Balance
         */
        startBalance: () => LocalizedString;
      };
      labels: {
        /**
         * Income
         */
        income: () => LocalizedString;
        /**
         * Tax
         */
        tax: () => LocalizedString;
        /**
         * Interest
         */
        interest: () => LocalizedString;
        /**
         * Gain / Loss
         */
        gainLoss: () => LocalizedString;
        /**
         * Equity
         */
        equity: () => LocalizedString;
        /**
         * Liabilities
         */
        liabilities: () => LocalizedString;
        /**
         * Expenses
         */
        expenses: () => LocalizedString;
      };
      summary: {
        /**
         * Start
         */
        start: () => LocalizedString;
        /**
         * End
         */
        end: () => LocalizedString;
        /**
         * change
         */
        change: () => LocalizedString;
      };
      messages: {
        /**
         * Oops! You have not made any transactions for the selected year.
         */
        noTransactions: () => LocalizedString;
      };
    };
    scheduleAl: {
      headers: {
        /**
         * Code
         */
        code: () => LocalizedString;
        /**
         * Section
         */
        section: () => LocalizedString;
        /**
         * Details
         */
        details: () => LocalizedString;
        /**
         * Amount
         */
        amount: () => LocalizedString;
      };
      /**
       * Schedule AL as on
       */
      asOn: () => LocalizedString;
    };
    capitalGains: {
      summary: {
        /**
         * Withdrawn
         */
        withdrawn: () => LocalizedString;
        /**
         * Gain
         */
        gain: () => LocalizedString;
        /**
         * Taxable Gain
         */
        taxableGain: () => LocalizedString;
        /**
         * Short Term Tax
         */
        shortTermTax: () => LocalizedString;
        /**
         * Long Term Tax
         */
        longTermTax: () => LocalizedString;
        /**
         * Taxable at Slab Rate
         */
        taxableAtSlabRate: () => LocalizedString;
      };
      columns: {
        /**
         * Account
         */
        account: () => LocalizedString;
        /**
         * Tax Category
         */
        taxCategory: () => LocalizedString;
        /**
         * Sold Units
         */
        soldUnits: () => LocalizedString;
        /**
         * Purchase Price
         */
        purchasePrice: () => LocalizedString;
        /**
         * Average Purchase Unit Price
         */
        averagePurchaseUnitPrice: () => LocalizedString;
        /**
         * Sell Price
         */
        sellPrice: () => LocalizedString;
        /**
         * Average Sell Unit Price
         */
        averageSellUnitPrice: () => LocalizedString;
        /**
         * Gain
         */
        gain: () => LocalizedString;
        /**
         * Taxable Gain
         */
        taxableGain: () => LocalizedString;
        /**
         * Short Term Tax
         */
        shortTermTax: () => LocalizedString;
        /**
         * Long Term Tax
         */
        longTermTax: () => LocalizedString;
        /**
         * Taxable at Slab Rate
         */
        taxableAtSlabRate: () => LocalizedString;
      };
      detail: {
        /**
         * Purchase Date
         */
        purchaseDate: () => LocalizedString;
        /**
         * Purchase Price
         */
        purchasePrice: () => LocalizedString;
        /**
         * Sell Date
         */
        sellDate: () => LocalizedString;
        /**
         * Sell Price
         */
        sellPrice: () => LocalizedString;
        /**
         * Gain
         */
        gain: () => LocalizedString;
        /**
         * Taxable Gain
         */
        taxableGain: () => LocalizedString;
        /**
         * Short Term Tax
         */
        shortTermTax: () => LocalizedString;
        /**
         * Long Term Tax
         */
        longTermTax: () => LocalizedString;
        /**
         * Taxable at Slab Rate
         */
        taxableAtSlabRate: () => LocalizedString;
      };
    };
    priceCodeSearch: {
      /**
       * Choose Price Provider
       */
      title: () => LocalizedString;
      /**
       * Provider
       */
      provider: () => LocalizedString;
      /**
       * Select
       */
      select: () => LocalizedString;
      /**
       * Cancel
       */
      cancel: () => LocalizedString;
      /**
       * Clear Provider Cache
       */
      clearProviderCache: () => LocalizedString;
    };
    bulkEdit: {
      /**
       * Rename Account
       */
      renameAccount: () => LocalizedString;
      /**
       * Old Account name
       */
      oldAccountName: () => LocalizedString;
      /**
       * New Account name
       */
      newAccountName: () => LocalizedString;
      /**
       * Preview
       */
      preview: () => LocalizedString;
    };
    dateRange: {
      /**
       * All
       */
      all: () => LocalizedString;
      /**
       * 10 years
       */
      tenYears: () => LocalizedString;
      /**
       * 5 years
       */
      fiveYears: () => LocalizedString;
      /**
       * 3 years
       */
      threeYears: () => LocalizedString;
      /**
       * 1 year
       */
      oneYear: () => LocalizedString;
    };
  };
  spreadsheet: {
    /**
     * Unsupported file type {extension}
     */
    unsupportedFileType: (arg: { extension: unknown }) => LocalizedString;
    /**
     * Please enter the password to open this XLSX file. Press cancel to exit.
     */
    passwordPrompt: () => LocalizedString;
    /**
     * Password required.
     */
    passwordRequired: () => LocalizedString;
    /**
     * Unable to parse Password protected XLSX
     */
    unableToParsePasswordProtected: () => LocalizedString;
  };
  sync: {
    /**
     * Failed to sync
     */
    failedToSync: () => LocalizedString;
  };
  transactionSequence: {
    /**
     * weekly
     */
    weekly: () => LocalizedString;
    /**
     * bi-weekly
     */
    biWeekly: () => LocalizedString;
    /**
     * monthly
     */
    monthly: () => LocalizedString;
    /**
     * quarterly
     */
    quarterly: () => LocalizedString;
    /**
     * half-yearly
     */
    halfYearly: () => LocalizedString;
    /**
     * yearly
     */
    yearly: () => LocalizedString;
    /**
     * every {days} days
     */
    everyDays: (arg: { days: unknown }) => LocalizedString;
  };
  pdf: {
    /**
     * Please enter the password to open this PDF file. Press cancel to exit.
     */
    passwordPrompt: () => LocalizedString;
    /**
     * Password required.
     */
    passwordRequired: () => LocalizedString;
  };
  editor: {
    /**
     * Invalid syntax
     */
    invalidSyntax: () => LocalizedString;
    /**
     * Invalid date
     */
    invalidDate: () => LocalizedString;
    /**
     * {property} cannot be used with {operator} and {type}
     */
    cannotUseWith: (arg: {
      operator: unknown;
      property: unknown;
      type: unknown;
    }) => LocalizedString;
  };
  dashboard: {
    emptyState: {
      /**
       * Looks like you are new here, you can either get started or look at a demo setup
       */
      title: () => LocalizedString;
      getStarted: {
        /**
         * I want to get started
         */
        title: () => LocalizedString;
        /**
         * Go to configuration page and set your default currency and locale.
         */
        step1: () => LocalizedString;
        /**
         * Go to editor page and start adding transactions to your journal.
         */
        step2: () => LocalizedString;
        /**
         * configuration
         */
        configLink: () => LocalizedString;
        /**
         * editor
         */
        editorLink: () => LocalizedString;
      };
      viewDemo: {
        /**
         * I want to view a Demo
         */
        title: () => LocalizedString;
        /**
         * Click the button below to load a demo setup. This will load a demo journal with relevant config.
         */
        step1: () => LocalizedString;
        /**
         * Once you are done playing around, you can go to editor page and select all the content and delete them.
         */
        step2: () => LocalizedString;
        /**
         * Go to configuration page and click the reset to defaults button.
         */
        step3: () => LocalizedString;
        /**
         * editor
         */
        editorLink: () => LocalizedString;
        /**
         * configuration
         */
        configLink: () => LocalizedString;
      };
      /**
       * Setup Demo
       */
      setupDemo: () => LocalizedString;
    };
    assets: {
      /**
       * Net worth
       */
      netWorth: () => LocalizedString;
      /**
       * Net Investment
       */
      netInvestment: () => LocalizedString;
      /**
       * Gain / Loss
       */
      gainLoss: () => LocalizedString;
      /**
       * Checking Balance
       */
      checkingBalance: () => LocalizedString;
    };
    cashFlow: {
      /**
       * Oops! You have not made any transactions in the last 3 months.
       */
      emptyState: () => LocalizedString;
    };
    expenses: {
      /**
       * Hurray! You have no expenses this month.
       */
      emptyState: () => LocalizedString;
    };
    /**
     * Recent Transactions
     */
    recentTransactions: () => LocalizedString;
  };
  config: {
    /**
     * Prices are <b>not</b> automatically updated after config change. Use the menu at the top right corner to update prices. If the journal failed to sync due to any issues, fix the issues and use the menu to sync again.
     */
    warning: () => LocalizedString;
    /**
     * Save
     */
    save: () => LocalizedString;
    /**
     * Cancel
     */
    cancel: () => LocalizedString;
    /**
     * Reset to Defaults
     */
    resetToDefaults: () => LocalizedString;
    /**
     * Are you sure you want to reset the config to defaults? This action is not reversible.
     */
    resetConfirm: () => LocalizedString;
    /**
     * Saved config
     */
    saved: () => LocalizedString;
  };
  about: {
    /**
     * Version
     */
    version: () => LocalizedString;
    /**
     * Links
     */
    links: () => LocalizedString;
  };
  import: {
    /**
     * Failed to save {name}. reason: {reason}
     */
    failedToSave: (arg: { name: unknown; reason: unknown }) => LocalizedString;
    /**
     * Saved {name}
     */
    saved: (arg: { name: unknown }) => LocalizedString;
    /**
     * Are you sure you want to delete {name} template?
     */
    deleteConfirm: (arg: { name: unknown }) => LocalizedString;
    /**
     * Failed to remove {name}. reason: {reason}
     */
    failedToRemove: (arg: { name: unknown; reason: unknown }) => LocalizedString;
    /**
     * Removed {name}
     */
    removed: (arg: { name: unknown }) => LocalizedString;
  };
  price: {
    /**
     * Price cache cleared.
     */
    cacheCleared: () => LocalizedString;
  };
};

export type Formatters = {};
